// <auto-generated />
using EFKomNU.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFKomNU.Migrations
{
    [DbContext(typeof(UnikContext))]
    [Migration("20221203130122_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFKomNU.Model.Kompetence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KompetenceEntities");
                });

            modelBuilder.Entity("EFKomNU.Model.Medarbejder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tlf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedarbejderEntities");
                });

            modelBuilder.Entity("KompetenceMedarbejder", b =>
                {
                    b.Property<int>("KompetenceListeId")
                        .HasColumnType("int");

                    b.Property<int>("KompetenceListeId1")
                        .HasColumnType("int");

                    b.HasKey("KompetenceListeId", "KompetenceListeId1");

                    b.HasIndex("KompetenceListeId1");

                    b.ToTable("KompetenceMedarbejder");
                });

            modelBuilder.Entity("KompetenceMedarbejder", b =>
                {
                    b.HasOne("EFKomNU.Model.Kompetence", null)
                        .WithMany()
                        .HasForeignKey("KompetenceListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFKomNU.Model.Medarbejder", null)
                        .WithMany()
                        .HasForeignKey("KompetenceListeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
